version: "3"
services:
  app:
    container_name: dev_github_blog_app
    build:
      context: ./
      dockerfile: Dockerfile.dev
    tty: true
    volumes:
    - ./:/var/www
    ports:
    - "5000:5000"
    networks:
    - dev_github_blog_network

networks:
  dev_github_blog_network:
